name: qiniu_sdk_base
version: 0.5.2
homepage: https://github.com/qiniu/dart-sdk
description: The sdk basic of Qiniu products

false_secrets:
  - /test/auth/auth_test.dart

environment:
  sdk: ">=3.3.0 <3.4.0"

dependencies:
  dio: ^5.5.0
  crypto: ^3.0.3
  meta: ^1.15.0
  uuid: ^4.4.2
  path: ^1.9.0

dev_dependencies:
  test:
  lints:
  dotenv: ^4.1.0
  coverage: "^1.6.3"
